### ISSUE TITLE
Cant get this to work

### ISSUE THREAD

**Issue by paccloud** [neondatabase/mcp-server-neon#2]
I am struggling to get this fully functional. I have not used the MCP installers with other servers but I do have many other MCP servers running. 

I try to run the commands in the readme in my directory of my project for my local dev and I can not get it to connect. 

Any ideas are welcome

**Comment by davidgomes** [comment]
@paccloud can you please share any errors, screenshots, video so we can better help you?

**Comment by pffigueiredo** [comment]
I reproduced the issue by:
1. Removing the `dist` folder
2. Regenerating it using `npm run watch`

The root cause was that the `dist` folder lacked proper execution permissions - I'm going to do a quick patch, but for the time being, giving the local executable permissions directly should do the trick.

e.g.

```bash
chmod +x /mcp-server-neon/dist/index.js 
```

**Comment by pffigueiredo** [comment]
Pull the repository and re-run:

```
npm install
npm run watch
node dist/index.js init $NEON_API_KEY
```

Everything should be back in order 💪
